defaults: &defaults
  exam:
    question_type:
      single_choice: "single choice"
      multiple_choice: "multiple choice"
      text: "text"
    state:
      finish: "Finish"
  status:
    start: "start"
    testing: "testing"
    checked: "checked"
    unchecked: "unchecked"
  questions:
    state:
      waiting: "waiting"
      accepted: "accepted"
      rejected: "rejected"
  pagination:
    per_page: 25
  default_num_of_most_failed_question: 5
  min_num_of_most_failed_question: 2
  max_num_of_most_failed_question: 20

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
